const Sentiment = require('sentiment');
const axios = require('axios');
const sentiment = new Sentiment();

// I've pre-filled your key and your specific video URL
const API_KEY = '84c616f955mshf5366a38a6a9b8bp157011jsn0db1ee174b05'; 
const TARGET_URL = "https://www.tiktok.com/@vanilla_gorillamma/video/7609430797254266134";

async function analyzeComments(videoUrl) {
    console.log(`\n--- SCANNING LIVE TIKTOK ---`);
        console.log(`Target: ${videoUrl}`);
            console.log(`Connecting... please wait...\n`);
                
                    const options = {
                            method: 'GET',
                                    url: 'https://tiktok-scraper7.p.rapidapi.com/comment/list',
                                            params: {url: videoUrl, count: '15'}, // Grabbing 15 comments
                                                    headers: {
                                                                'x-rapidapi-key': API_KEY,
                                                                            'x-rapidapi-host': 'tiktok-scraper7.p.rapidapi.com'
                                                                                    }
                                                                                        };

                                                                                            try {
                                                                                                    const response = await axios.request(options);
                                                                                                            
                                                                                                                    // TikTok API structures vary; this safely finds the comment list
                                                                                                                            const comments = response.data?.data?.comments || response.data?.comments;

                                                                                                                                    if (!comments || comments.length === 0) {
                                                                                                                                                console.log("No comments found. This can happen if the video is private or the API is busy.");
                                                                                                                                                            return;
                                                                                                                                                                    }

                                                                                                                                                                            comments.forEach((c, i) => {
                                                                                                                                                                                        const text = c.text || "No text";
                                                                                                                                                                                                    const user = c.author?.nickname || "Unknown User";
                                                                                                                                                                                                                const score = sentiment.analyze(text).score;
                                                                                                                                                                                                                            
                                                                                                                                                                                                                                        let vibe = '😐 NEUTRAL';
                                                                                                                                                                                                                                                    if (score > 0) vibe = '✅ POSITIVE';
                                                                                                                                                                                                                                                                if (score < 0) vibe = '❌ NEGATIVE';

                                                                                                                                                                                                                                                                            console.log(`[${i+1}] @${user}: ${text}`);
                                                                                                                                                                                                                                                                                        console.log(`Verdict: ${vibe} (Score: ${score})\n`);
                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                        console.log("--- SCAN COMPLETE ---");
                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                    console.error("Error grabbing data:", error.message);
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                        analyzeComments(TARGET_URL);
                                                                                                                                                                                                                                                                                                                        const Sentiment = require('sentiment');
                                                                                                                                                                                                                                                                                                                        const axios = require('axios');
                                                                                                                                                                                                                                                                                                                        const sentiment = new Sentiment();

                                                                                                                                                                                                                                                                                                                        // I've pre-filled your key and your specific video URL
                                                                                                                                                                                                                                                                                                                        const API_KEY = '84c616f955mshf5366a38a6a9b8bp157011jsn0db1ee174b05'; 
                                                                                                                                                                                                                                                                                                                        const TARGET_URL = "https://www.tiktok.com/@vanilla_gorillamma/video/7609430797254266134";

                                                                                                                                                                                                                                                                                                                        async function analyzeComments(videoUrl) {
                                                                                                                                                                                                                                                                                                                            console.log(`\n--- SCANNING LIVE TIKTOK ---`);
                                                                                                                                                                                                                                                                                                                                console.log(`Target: ${videoUrl}`);
                                                                                                                                                                                                                                                                                                                                    console.log(`Connecting... please wait...\n`);
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                            const options = {
                                                                                                                                                                                                                                                                                                                                                    method: 'GET',
                                                                                                                                                                                                                                                                                                                                                            url: 'https://tiktok-scraper7.p.rapidapi.com/comment/list',
                                                                                                                                                                                                                                                                                                                                                                    params: {url: videoUrl, count: '15'}, // Grabbing 15 comments
                                                                                                                                                                                                                                                                                                                                                                            headers: {
                                                                                                                                                                                                                                                                                                                                                                                        'x-rapidapi-key': API_KEY,
                                                                                                                                                                                                                                                                                                                                                                                                    'x-rapidapi-host': 'tiktok-scraper7.p.rapidapi.com'
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                                                            const response = await axios.request(options);
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                            // TikTok API structures vary; this safely finds the comment list
                                                                                                                                                                                                                                                                                                                                                                                                                                                    const comments = response.data?.data?.comments || response.data?.comments;

                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!comments || comments.length === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log("No comments found. This can happen if the video is private or the API is busy.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    comments.forEach((c, i) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const text = c.text || "No text";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const user = c.author?.nickname || "Unknown User";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const score = sentiment.analyze(text).score;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let vibe = '😐 NEUTRAL';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (score > 0) vibe = '✅ POSITIVE';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (score < 0) vibe = '❌ NEGATIVE';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log(`[${i+1}] @${user}: ${text}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log(`Verdict: ${vibe} (Score: ${score})\n`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log("--- SCAN COMPLETE ---");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error("Error grabbing data:", error.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                analyzeComments(TARGET_URL);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                